name: publish-docker-image

on:
    push:
        branches:
            - "master"

jobs:
  publish-docker-image-on-github-cr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: "JayantGoel001"
        password: ${{ secrets.CONTAINER_REGISTRY }}

    - name: Build and Push the Docker image of jupyter-x-docker on Github Container Registry
      run: |
        docker build -t ghcr.io/jayantgoel001/jupyter-x-docker:latest .
        docker push ghcr.io/jayantgoel001/jupyter-x-docker:latest

  publish-docker-image-on-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
            username: "jayantgoel001"
            password: ${{ secrets.DOCKERHUB }}

      - name: Build and Push the Docker image of jupyter-x-docker on Dockerhub
        run: |
          docker build -t jayantgoel001/jupyter-x-docker:latest .
          docker push jayantgoel001/jupyter-x-docker:latest

  deploy-docker-image-on-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Build, Push and Deploy a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: "jayantgoel001@gmail.com"
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "jupyter-x-docker"